function C = ctrl_student_observer_C(u,v,r)
%CTRL_STUDENT_OBSERVER_C
%    C = CTRL_STUDENT_OBSERVER_C(U,V,R)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    09-Feb-2016 16:30:14

t2 = u.*1.679e1;
C = reshape([0.0,0.0,r.*5.54625e-1+v.*2.479e1,0.0,0.0,-t2,r.*(-5.54625e-1)-v.*2.479e1,t2,0.0],[3, 3]);
